version: '3'

tasks:
  cmake-debug:
    desc: Set up CMake debug build directory in build.debug
    sources:
      - CMakeLists.txt
    cmds:
      - cmake -H. -Bbuild.debug -GNinja -DCMAKE_BUILD_TYPE=Debug
      - rm -f build
      - ln -s build.debug build
    generates:
      - build.debug/build.ninja
  cmake-release:
    desc: Set up CMake release build directory in build.release
    sources:
      - CMakeLists.txt
    cmds:
      - cmake -H. -Bbuild.release -GNinja -DCMAKE_BUILD_TYPE=Release
      - rm -f build
      - ln -s build.release build
    generates:
      - build.release/build.ninja
  build-debug:
    desc: Build in debug mode, along with unit tests, in build.debug
    deps:
      - cmake-debug
    sources:
      - src/**/*
      - test/**/*
      - vendor/**/*
    cmds:
      - ninja -C build.debug
    generates:
      - build.debug/test
      - build.debug/ludwig
  build-release:
    desc: Build in release mode,  in build.release
    deps:
      - cmake-release
    sources:
      - src/**/*
      - test/**/*
      - vendor/**/*
    cmds:
      - ninja -C build.release
    generates:
      - build.release/ludwig
  test:
    desc: Run unit test suite
    deps:
      - build-debug
    cmds:
      - gdb -quiet -ex='set confirm on' -ex=run -ex=quit --args ./build.debug/test -b
  run-debug:
    deps:
      - build-debug
    cmds:
      - ./build.debug/ludwig
  run:
    deps:
      - build-release
    cmds:
      - ./build.release/ludwig
  html-sample:
    sources:
      - extras/static-sample-server.ts
      - extras/sample.html
      - static/*
    cmds:
      - deno run --allow-read --allow-net ./extras/static-sample-server.ts
  clean:
    desc: Delete all build directories
    cmds:
      - rm -rf build build.debug build.release
