version: '3'

tasks:
  cmake-debug:
    desc: ðŸ—ï¸ Set up CMake debug build directory in build.debug/
    sources:
      - CMakeLists.txt
    cmds:
      - cmake -H. -Bbuild.debug -GNinja -DCMAKE_BUILD_TYPE=Debug
      - rm -f build
      - ln -s build.debug build
    generates:
      - build.debug/build.ninja
  cmake-release:
    desc: ðŸ—ï¸ Set up CMake release build directory in build.release/
    sources:
      - CMakeLists.txt
    cmds:
      - cmake -H. -Bbuild.release -GNinja -DCMAKE_BUILD_TYPE=Release
      - rm -f build
      - ln -s build.release build
    generates:
      - build.release/build.ninja
  build-debug:
    desc: ðŸ”§ Build in debug mode, along with unit tests, in build.debug/
    deps:
      - cmake-debug
    sources:
      - src/**/*
      - test/*.c++
      - test/*.h++
      - vendor/CMakeLists.txt
      - CMakeLists.txt
    cmds:
      - ninja -C build.debug
    generates:
      - build.debug/test
      - build.debug/ludwig
  build-release:
    desc: ðŸ”§ Build in release mode, in build.release/
    deps:
      - cmake-release
    sources:
      - src/**/*
      - test/*.c++
      - test/*.h++
      - vendor/CMakeLists.txt
      - CMakeLists.txt
    cmds:
      - ninja -C build.release
    generates:
      - build.release/ludwig
  test:
    desc: ðŸš¨ Run the unit test suite
    deps:
      - build-debug
    cmds:
      - lldb -o run -- ./build.debug/test -b
  run-debug:
    desc: â–¶ï¸ Run the debug build of Ludwig, with default settings
    deps:
      - build-debug
    cmds:
      - ./build.debug/ludwig --log-level debug
  run:
    desc: â–¶ï¸ Run the release build of Ludwig, with default settings
    deps:
      - build-release
    cmds:
      - ./build.release/ludwig
  gen-typescript-flatbuffers:
    desc: âš™ï¸ Generate TypesScript Flatbuffers files used by the scripts in extras/
    sources:
      - src/models/*.fbs
    cmds:
      - ./build.debug/flatc --ts --gen-all -o ./extras/flatbuffers src/models/ts-models.fbs
      - >
        find ./extras/flatbuffers -iname '*.ts' -exec sed -i -e "s/\\.js'/.ts'/g" -e "s/from 'flatbuffers'/from 'npm:flatbuffers'/g" {} \;
    generates:
      - ./extras/flatbuffers/ludwig.ts
  gen-random-db:
    desc: "âš™ï¸ Generate a ludwig.db file with random test fixture data. âš ï¸ WARNING: WILL DELETE AN EXISTING DB FILE! âš ï¸"
    deps:
      - gen-typescript-flatbuffers
      - build-debug
    cmds:
      - rm -f ludwig.mdb
      - rm -f ludwig.mdb-lock
      - deno run extras/generate-mock-data.ts > random.dbdump.gz
      - ./build.debug/ludwig --log-level debug --import random.dbdump.gz
  html-sample:
    sources:
      - extras/static-sample-server.ts
      - extras/sample.html
      - src/static/*
    cmds:
      - deno run --allow-read --allow-net ./extras/static-sample-server.ts
  clean:
    desc: ðŸ§¹ Delete all build directories
    cmds:
      - rm -rf build build.debug build.release
