// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum BoardSortType {
  New = 0,
  Old = 1,
  MostSubscribers = 2,
  MostPosts = 3,
  NewPosts = 4
}
