// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum CommentSortType {
  Hot = 0,
  New = 1,
  Old = 2,
  Top = 3
}
