// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum DumpType {
  User = 0,
  LocalUser = 1,
  Board = 2,
  LocalBoard = 3,
  Thread = 4,
  Comment = 5,
  Application = 6,
  Invite = 7,
  SettingRecord = 8,
  UpvoteBatch = 9,
  DownvoteBatch = 10,
  SubscriptionBatch = 11
}
