// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'npm:flatbuffers';

export class FbVoid {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FbVoid {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFbVoid(bb:flatbuffers.ByteBuffer, obj?:FbVoid):FbVoid {
  return (obj || new FbVoid()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFbVoid(bb:flatbuffers.ByteBuffer, obj?:FbVoid):FbVoid {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FbVoid()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startFbVoid(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endFbVoid(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFbVoid(builder:flatbuffers.Builder):flatbuffers.Offset {
  FbVoid.startFbVoid(builder);
  return FbVoid.endFbVoid(builder);
}
}
