// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum HomePageType {
  Subscribed = 0,
  Local = 1,
  All = 2,
  BoardList = 3,
  SingleBoard = 4
}
