// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ModActionTargetType {
  User = 0,
  Board = 1,
  Thread = 2,
  Comment = 3
}
