// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ModState {
  Visible = 0,
  Flagged = 1,
  Locked = 2,
  Removed = 3
}
