// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ModActionType {
  EditPost = 0,
  HidePost = 1,
  RemovePost = 2,
  PurgePost = 3,
  EditBoard = 4,
  RemoveBoard = 5,
  PurgeBoard = 6,
  EditUser = 7,
  TempBanUserFromBoard = 8,
  PermBanUserFromBoard = 9,
  TemBanUserFromInstance = 10,
  PermBanUserFromInstance = 11,
  PurgeUser = 12
}
