// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */



export enum PlainTextWithEmojis {
  NONE = 0,
  Plain = 1,
  CustomEmoji = 2
}

export function unionToPlainTextWithEmojis(
  type: PlainTextWithEmojis,
  accessor: (obj:string) => string|null
): string|null {
  switch(PlainTextWithEmojis[type]) {
    case 'NONE': return null; 
    case 'Plain': return accessor('') as string;
    case 'CustomEmoji': return accessor('') as string;
    default: return null;
  }
}

export function unionListToPlainTextWithEmojis(
  type: PlainTextWithEmojis, 
  accessor: (index: number, obj:string) => string|null, 
  index: number
): string|null {
  switch(PlainTextWithEmojis[type]) {
    case 'NONE': return null; 
    case 'Plain': return accessor(index, '') as string;
    case 'CustomEmoji': return accessor(index, '') as string;
    default: return null;
  }
}
