// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'npm:flatbuffers';

export class RichTextRef {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RichTextRef {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRichTextRef(bb:flatbuffers.ByteBuffer, obj?:RichTextRef):RichTextRef {
  return (obj || new RichTextRef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRichTextRef(bb:flatbuffers.ByteBuffer, obj?:RichTextRef):RichTextRef {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RichTextRef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startRichTextRef(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(1, id, BigInt('0'));
}

static endRichTextRef(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  return offset;
}

static createRichTextRef(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, id:bigint):flatbuffers.Offset {
  RichTextRef.startRichTextRef(builder);
  RichTextRef.addName(builder, nameOffset);
  RichTextRef.addId(builder, id);
  return RichTextRef.endRichTextRef(builder);
}
}
