// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { RichTextImage } from '../ludwig/rich-text-image.ts';


export enum RichText {
  NONE = 0,
  Text = 1,
  Emoji = 2,
  Link = 3,
  UserLink = 4,
  BoardLink = 5,
  Image = 6
}

export function unionToRichText(
  type: RichText,
  accessor: (obj:RichTextImage|string) => RichTextImage|string|null
): RichTextImage|string|null {
  switch(RichText[type]) {
    case 'NONE': return null; 
    case 'Text': return accessor('') as string;
    case 'Emoji': return accessor('') as string;
    case 'Link': return accessor('') as string;
    case 'UserLink': return accessor('') as string;
    case 'BoardLink': return accessor('') as string;
    case 'Image': return accessor(new RichTextImage())! as RichTextImage;
    default: return null;
  }
}

export function unionListToRichText(
  type: RichText, 
  accessor: (index: number, obj:RichTextImage|string) => RichTextImage|string|null, 
  index: number
): RichTextImage|string|null {
  switch(RichText[type]) {
    case 'NONE': return null; 
    case 'Text': return accessor(index, '') as string;
    case 'Emoji': return accessor(index, '') as string;
    case 'Link': return accessor(index, '') as string;
    case 'UserLink': return accessor(index, '') as string;
    case 'BoardLink': return accessor(index, '') as string;
    case 'Image': return accessor(index, new RichTextImage())! as RichTextImage;
    default: return null;
  }
}
