// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum SortType {
  Active = 0,
  Hot = 1,
  New = 2,
  Old = 3,
  MostComments = 4,
  NewComments = 5,
  TopAll = 6,
  TopYear = 7,
  TopSixMonths = 8,
  TopThreeMonths = 9,
  TopMonth = 10,
  TopWeek = 11,
  TopDay = 12,
  TopTwelveHour = 13,
  TopSixHour = 14,
  TopHour = 15
}
