// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'npm:flatbuffers';

export class SubscriptionRecord {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SubscriptionRecord {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSubscriptionRecord(bb:flatbuffers.ByteBuffer, obj?:SubscriptionRecord):SubscriptionRecord {
  return (obj || new SubscriptionRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSubscriptionRecord(bb:flatbuffers.ByteBuffer, obj?:SubscriptionRecord):SubscriptionRecord {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SubscriptionRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

board():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startSubscriptionRecord(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBoard(builder:flatbuffers.Builder, board:bigint) {
  builder.addFieldInt64(0, board, BigInt('0'));
}

static endSubscriptionRecord(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSubscriptionRecord(builder:flatbuffers.Builder, board:bigint):flatbuffers.Offset {
  SubscriptionRecord.startSubscriptionRecord(builder);
  SubscriptionRecord.addBoard(builder, board);
  return SubscriptionRecord.endSubscriptionRecord(builder);
}
}
