// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'npm:flatbuffers';

import { TextSpan, unionToTextSpan, unionListToTextSpan } from '../ludwig/text-span.ts';


export class TextLink {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TextLink {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTextLink(bb:flatbuffers.ByteBuffer, obj?:TextLink):TextLink {
  return (obj || new TextLink()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTextLink(bb:flatbuffers.ByteBuffer, obj?:TextLink):TextLink {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TextLink()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

href():string|null
href(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
href(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

spansType(index: number):TextSpan|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

spansTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

spansTypeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

spans(index: number, obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union_with_string(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
}

spansLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTextLink(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addHref(builder:flatbuffers.Builder, hrefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, hrefOffset, 0);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, titleOffset, 0);
}

static addSpansType(builder:flatbuffers.Builder, spansTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, spansTypeOffset, 0);
}

static createSpansTypeVector(builder:flatbuffers.Builder, data:TextSpan[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startSpansTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addSpans(builder:flatbuffers.Builder, spansOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, spansOffset, 0);
}

static createSpansVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSpansVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTextLink(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // href
  builder.requiredField(offset, 8) // spans_type
  builder.requiredField(offset, 10) // spans
  return offset;
}

static createTextLink(builder:flatbuffers.Builder, hrefOffset:flatbuffers.Offset, titleOffset:flatbuffers.Offset, spansTypeOffset:flatbuffers.Offset, spansOffset:flatbuffers.Offset):flatbuffers.Offset {
  TextLink.startTextLink(builder);
  TextLink.addHref(builder, hrefOffset);
  TextLink.addTitle(builder, titleOffset);
  TextLink.addSpansType(builder, spansTypeOffset);
  TextLink.addSpans(builder, spansOffset);
  return TextLink.endTextLink(builder);
}
}
