// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'npm:flatbuffers';

import { ModState } from '../ludwig/mod-state.ts';
import { TextBlock, unionToTextBlock, unionListToTextBlock } from '../ludwig/text-block.ts';


export class Thread {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Thread {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsThread(bb:flatbuffers.ByteBuffer, obj?:Thread):Thread {
  return (obj || new Thread()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsThread(bb:flatbuffers.ByteBuffer, obj?:Thread):Thread {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Thread()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

author():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

board():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

createdAt():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

updatedAt():bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : null;
}

instance():bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : null;
}

activityUrl():string|null
activityUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
activityUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

originalPostUrl():string|null
originalPostUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
originalPostUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

contentUrl():string|null
contentUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contentUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

contentTextRaw():string|null
contentTextRaw(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contentTextRaw(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

contentTextType(index: number):TextBlock|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

contentTextTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

contentTextTypeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

contentText(index: number, obj:any|string):any|string|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__union_with_string(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
}

contentTextLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

contentWarning():string|null
contentWarning(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
contentWarning(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

modState():ModState {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ModState.Visible;
}

modReason():string|null
modReason(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modReason(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startThread(builder:flatbuffers.Builder) {
  builder.startObject(15);
}

static addAuthor(builder:flatbuffers.Builder, author:bigint) {
  builder.addFieldInt64(0, author, BigInt('0'));
}

static addBoard(builder:flatbuffers.Builder, board:bigint) {
  builder.addFieldInt64(1, board, BigInt('0'));
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, titleOffset, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAt:bigint) {
  builder.addFieldInt64(3, createdAt, BigInt('0'));
}

static addUpdatedAt(builder:flatbuffers.Builder, updatedAt:bigint) {
  builder.addFieldInt64(4, updatedAt, BigInt(0));
}

static addInstance(builder:flatbuffers.Builder, instance:bigint) {
  builder.addFieldInt64(5, instance, BigInt(0));
}

static addActivityUrl(builder:flatbuffers.Builder, activityUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, activityUrlOffset, 0);
}

static addOriginalPostUrl(builder:flatbuffers.Builder, originalPostUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, originalPostUrlOffset, 0);
}

static addContentUrl(builder:flatbuffers.Builder, contentUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, contentUrlOffset, 0);
}

static addContentTextRaw(builder:flatbuffers.Builder, contentTextRawOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, contentTextRawOffset, 0);
}

static addContentTextType(builder:flatbuffers.Builder, contentTextTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, contentTextTypeOffset, 0);
}

static createContentTextTypeVector(builder:flatbuffers.Builder, data:TextBlock[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startContentTextTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addContentText(builder:flatbuffers.Builder, contentTextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, contentTextOffset, 0);
}

static createContentTextVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startContentTextVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addContentWarning(builder:flatbuffers.Builder, contentWarningOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, contentWarningOffset, 0);
}

static addModState(builder:flatbuffers.Builder, modState:ModState) {
  builder.addFieldInt8(13, modState, ModState.Visible);
}

static addModReason(builder:flatbuffers.Builder, modReasonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(14, modReasonOffset, 0);
}

static endThread(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 8) // title
  return offset;
}

static createThread(builder:flatbuffers.Builder, author:bigint, board:bigint, titleOffset:flatbuffers.Offset, createdAt:bigint, updatedAt:bigint|null, instance:bigint|null, activityUrlOffset:flatbuffers.Offset, originalPostUrlOffset:flatbuffers.Offset, contentUrlOffset:flatbuffers.Offset, contentTextRawOffset:flatbuffers.Offset, contentTextTypeOffset:flatbuffers.Offset, contentTextOffset:flatbuffers.Offset, contentWarningOffset:flatbuffers.Offset, modState:ModState, modReasonOffset:flatbuffers.Offset):flatbuffers.Offset {
  Thread.startThread(builder);
  Thread.addAuthor(builder, author);
  Thread.addBoard(builder, board);
  Thread.addTitle(builder, titleOffset);
  Thread.addCreatedAt(builder, createdAt);
  if (updatedAt !== null)
    Thread.addUpdatedAt(builder, updatedAt);
  if (instance !== null)
    Thread.addInstance(builder, instance);
  Thread.addActivityUrl(builder, activityUrlOffset);
  Thread.addOriginalPostUrl(builder, originalPostUrlOffset);
  Thread.addContentUrl(builder, contentUrlOffset);
  Thread.addContentTextRaw(builder, contentTextRawOffset);
  Thread.addContentTextType(builder, contentTextTypeOffset);
  Thread.addContentText(builder, contentTextOffset);
  Thread.addContentWarning(builder, contentWarningOffset);
  Thread.addModState(builder, modState);
  Thread.addModReason(builder, modReasonOffset);
  return Thread.endThread(builder);
}
}
