// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum UserSortType {
  New = 0,
  Old = 1,
  MostPosts = 2,
  NewPosts = 3
}
